# Generated by Django 4.1.9 on 2023-07-13 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0009_remove_subscription_is_active_subscription_user'),
        ('USER', '0012_connections_document_file_connections_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_active_subscription', to='ADMIN.subscription'),
        ),
    ]
